/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-02-06 15:19:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/Views/header.jsp", Long.valueOf(1485959801739L));
    _jspx_dependants.put("/WEB-INF/Views/footer.jsp", Long.valueOf(1485884658117L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/index.css\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Home -penandpaper.in</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"Resources/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"Resources/css/header.css\">\r\n");
      out.write("  <link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"Resources/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("   <script>\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("   $('.dropdown-submenu a.test').on(\"click\", function(e){\r\n");
      out.write("   $(this).next('ul').toggle();\r\n");
      out.write("   e.stopPropagation();\r\n");
      out.write("   e.preventDefault();\r\n");
      out.write("    });\r\n");
      out.write("   });\r\n");
      out.write("  </script>\r\n");
      out.write(" </head>\r\n");
      out.write(" \r\n");
      out.write("  <div id=\"header\" class=\"jumbotron\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("  <div class =\"col-sm-2\">\r\n");
      out.write("  <a   class=\"img-responsive2\" class=\"navbar-brand\" href=\"home\"><img id =\"brand\" src=\"Resources/images/logo.png\"><img/></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-sm-10\">\r\n");
      out.write("  <a   class=\"img-responsive\"  class=\"navbar-brand\" href=\"#\"><img id=\"banner\" src=\"Resources/images/banner.jpg\"><img/></a>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\t\r\n");
      out.write("  </div>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <!-- Header and navbar -->\r\n");
      out.write("\r\n");
      out.write(" <nav style=\"background-color:#26254F\" class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("    <ul id =\"navbar\" class=\"nav navbar-nav\">\r\n");
      out.write("    <li class=\"active\"><a href=\"home\"><span class=\"glyphicon glyphicon-home\"></span>  Home</a></li>\r\n");
      out.write("    <li class=\"dropdown\">\r\n");
      out.write("          <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"><span class=\"glyphicon glyphicon-paperclip\"></span>   Categories <span class=\"caret\"></span></a>\r\n");
      out.write("    <ul class=\"dropdown-menu\">\r\n");
      out.write("    <li class=\"dropdown-submenu\">\r\n");
      out.write("          <a class=\"test\" tabindex=\"-1\" href=\"#\">Archies <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul  class=\"dropdown-menu\">\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Albums</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">AutogGraph Book</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Diary</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Invitation Card</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Notebooks</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Record Book</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Scrap Book</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <a class=\"test\" tabindex=\"-1\" href=\"#\">Games & Toys <span class=\"caret\"></span></a>\r\n");
      out.write("        <ul  class=\"dropdown-menu\">\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Art & craft</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Board Games</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">General</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Learning</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Magic Games</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Preschool</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Purses & cases</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Puzzles</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Writing Boards</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("           <a class=\"test\" tabindex=\"-1\" href=\"#\">Home Decor <span class=\"caret\"></span></a>\r\n");
      out.write("           <ul  class=\"dropdown-menu\">\r\n");
      out.write("           <li><a tabindex=\"-1\" href=\"#\">Decor & Furnishings</a></li>\r\n");
      out.write("           <li><a tabindex=\"-1\" href=\"#\">Home Furniture</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("           <a class=\"test\" tabindex=\"-1\" href=\"#\">House Keeping <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul  class=\"dropdown-menu\">\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Cleaning Chemicals</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Cleaning Cloths</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Dustbins and Bags</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Package Materials</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Tissues and Napkins</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("          <a class=\"test\" tabindex=\"-1\" href=\"#\">Office Stationery <span class=\"caret\"></span></a>\r\n");
      out.write("          <ul  class=\"dropdown-menu\">\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Battery & Chargers</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Binder Clips & Pins</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Board & Markers</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Calculators</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Computer & Peripherals</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Correction Fluids</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Diary & Planners</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">File & Folders</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Glues & Adhesives</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Office Machines</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Pads & Notebooks</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Punching Machines</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Scales & Rulers</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Scissors & Cutters</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Stamp Pads & Inks</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Staplers & Pins</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Sticky Notes & Flags</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Tapes & Dispensers</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("        <a class=\"test\" tabindex=\"-1\" href=\"#\">Paper Products<span class=\"caret\"></span></a>\r\n");
      out.write("        <ul  class=\"dropdown-menu\">\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Art & Craft Paper</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Computer labels</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Copier Paper</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Copy & Register</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Flip Charts</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Paper Envelops</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Rolles & Plotters</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Speciality Papers</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Transparent Sheets</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">White & Color Design Sheets</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Pads & Notebooks</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("           <a class=\"test\" tabindex=\"-1\" href=\"#\">Party Essentials<span class=\"caret\"></span></a>\r\n");
      out.write("        <ul  class=\"dropdown-menu\">\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Balloons</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Invitation Cards</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Gift Baskets</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Return Gifts</a></li>\r\n");
      out.write("       </ul>\r\n");
      out.write("        <a class=\"test\" tabindex=\"-1\" href=\"#\">School Stationery <span class=\"caret\"></span></a>\r\n");
      out.write("        <ul  class=\"dropdown-menu\">\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Art & Craft</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Books</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Bottles & Sippers</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Colors & Brushes</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Engg Instruments</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Eraser & Sharpner</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Exam Boards & Pads</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Gift Sets</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Lunch Boxes</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Pencil Box</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Student Notebook</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("          <a class=\"test\" tabindex=\"-1\" href=\"#\">Writing Instruments <span class=\"caret\"></span></a>\r\n");
      out.write("        <ul  class=\"dropdown-menu\">\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Ball Pens</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Chalks</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Fountain Pens</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Gel Pens</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Glitter Pens</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Highligters</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Markers</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Mech Pencils</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Parker Pens</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Pencils</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Pilot Pens</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Reffils & Inks</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Roller Pens</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Rotring Pens</a></li>\r\n");
      out.write("          <li><a tabindex=\"-1\" href=\"#\">Signature Pens</a></li>\r\n");
      out.write("       </ul>\r\n");
      out.write("     </ul>\r\n");
      out.write("   </li>\r\n");
      out.write("        <li><a href=\"aboutus\"><span class=\"glyphicon glyphicon-user\"></span>  About Us</a></li>\r\n");
      out.write("        <li><a href=\"contactus\"><span class=\"glyphicon glyphicon-phone-alt\"></span>  Contact Us</a></li>\r\n");
      out.write("   </ul>\r\n");
      out.write("     \r\n");
      out.write("        <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li><a href=\"register\"><span class=\"glyphicon glyphicon-pencil\"></span>    Register</a></li>\r\n");
      out.write("        <li><a href=\"login\"><span class=\"glyphicon glyphicon-log-in\"></span>    Login</a></li>\r\n");
      out.write("        <li><a href=\"#\"><span class=\"glyphicon glyphicon-shopping-cart\"></span>    Shopping Cart:0</a></li>\r\n");
      out.write("       </ul>\r\n");
      out.write("    </div>\r\n");
      out.write(" </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<body style=\"background-color:#EEEEEE;\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <br>\r\n");
      out.write("  <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <!-- Indicators -->\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("    </ol>\r\n");
      out.write("\r\n");
      out.write("    <!-- Wrapper for slides -->\r\n");
      out.write("    <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("      <div class=\"item active\">\r\n");
      out.write("        <img src=\"Resources/images/slide1.png\" alt=\"slide1\" width=\"460\" height=\"345\">\r\n");
      out.write("          <div class=\"carousel-caption\">\r\n");
      out.write("          <h3 class=\"carouselcaption\">OFFICE & HOUSEKEEPING SUPPLIES</h3>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"Resources/images/slide2.png\" alt=\"slide2\" width=\"460\" height=\"345\">\r\n");
      out.write("          <div class=\"carousel-caption\">\r\n");
      out.write("          <h3 class=\"carouselcaption\">Save upto 50% on Painter Combo Pack</h3>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"Resources/images/slide3.png\" alt=\"slide3\" width=\"460\" height=\"345\">\r\n");
      out.write("        <div class=\"carousel-caption\">\r\n");
      out.write("        <h3 class=\"carouselcaption\">Best School Stationery products</h3>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"Resources/images/slide4.png\" alt=\"slide4\" width=\"460\" height=\"345\">\r\n");
      out.write("        <div class=\"carousel-caption\">\r\n");
      out.write("        <a href=\"#\"><img  style=\"width:400px;height:200px;float:left;margin:50px;\"  src=\"Resources/images/discount.jpg\"></img>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Left and right controls -->\r\n");
      out.write("    <a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Previous</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Next</span>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("      \r\n");
      out.write("         <div class=\"container\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("         <div class =\"col-sm-4 col-xs-12\"><a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("         <img class=\"img-responsive\" src=\"Resources/images/scl.png\" alt=\"\"></a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class =\"col-sm-4 col-xs-12\"><a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("         <img class=\"img-responsive\" src=\"Resources/images/office.png\" alt=\"\">\r\n");
      out.write("         </a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class =\"col-sm-4 col-xs-12\">\r\n");
      out.write("         <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("         <img class=\"img-responsive\" src=\"Resources/images/art.png\" alt=\"\">\r\n");
      out.write("         </a>                      \r\n");
      out.write("         </div>\r\n");
      out.write("       \r\n");
      out.write("       <div class =\"col-sm-4 col-xs-12\">\r\n");
      out.write("       <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("       <img class=\"img-responsive\" src=\"Resources/images/party.png\" alt=\"\">\r\n");
      out.write("       </a>                      \r\n");
      out.write("       </div>\r\n");
      out.write("        <div class =\"col-sm-4 col-xs-12\">\r\n");
      out.write("       <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("       <img class=\"img-responsive\" src=\"Resources/images/envelopes.png\" alt=\"\">\r\n");
      out.write("       </a>                      \r\n");
      out.write("       </div>\r\n");
      out.write("       <div class =\"col-sm-4 col-xs-12\">\r\n");
      out.write("       <a class=\"thumbnail\" href=\"#\">\r\n");
      out.write("       <img class=\"img-responsive\" src=\"Resources/images/officemachines.png\" alt=\"\">\r\n");
      out.write("       </a>                      \r\n");
      out.write("       </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr style=\"height:1px; background-color:white;\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-9\">\r\n");
      out.write("                <h3>\r\n");
      out.write("                    BEST SELLERS</h3>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-3\">\r\n");
      out.write("                <!-- Controls -->\r\n");
      out.write("                <div class=\"controls pull-right hidden-xs\">\r\n");
      out.write("                    <a class=\"left fa fa-chevron-left btn btn-success\" href=\"#carousel-example\"\r\n");
      out.write("                        data-slide=\"prev\"></a><a class=\"right fa fa-chevron-right btn btn-success\" href=\"#carousel-example\"\r\n");
      out.write("                            data-slide=\"next\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"carousel-example\" class=\"carousel slide hidden-xs\" data-ride=\"carousel\">\r\n");
      out.write("            <!-- Wrapper for slides -->\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"item active\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <div class=\"col-item\">\r\n");
      out.write("                                <div class=\"photo\">\r\n");
      out.write("                                    <img src=\"Resources/images/color chalk.jpeg\" class=\"img-responsive\" alt=\"a\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"price col-sm-6\">\r\n");
      out.write("                                            <h5>\r\n");
      out.write("                                                Color Chalk</h5>\r\n");
      out.write("                                            <h5 class=\"price-text-color\">\r\n");
      out.write("                                                &#8377;199.99</h5>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"rating hidden-sm col-sm-6\">\r\n");
      out.write("                                            <i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"separator clear-left\">\r\n");
      out.write("                                        <p class=\"btn-add\">\r\n");
      out.write("                                            <i class=\"fa fa-shopping-cart\"></i><a href=\"#\" class=\"hidden-sm\">Add to cart</a></p>\r\n");
      out.write("                                        <p class=\"btn-details\">\r\n");
      out.write("                                            <i class=\"fa fa-list\"></i><a href=\"#\" class=\"hidden-sm\">More details</a></p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"clearfix\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <div class=\"col-item\">\r\n");
      out.write("                                <div class=\"photo\">\r\n");
      out.write("                                    <img src=\"Resources/images/liquid gum tube.jpg\" class=\"img-responsive\" alt=\"a\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"price col-sm-6\">\r\n");
      out.write("                                            <h5>\r\n");
      out.write("                                                Liquid Gum Tube</h5>\r\n");
      out.write("                                            <h5 class=\"price-text-color\">\r\n");
      out.write("                                                &#8377;50.00</h5>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"rating hidden-sm col-sm-6\">\r\n");
      out.write("                                         <i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"fa fa-star\"></i>\r\n");
      out.write("                                       \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"separator clear-left\">\r\n");
      out.write("                                        <p class=\"btn-add\">\r\n");
      out.write("                                            <i class=\"fa fa-shopping-cart\"></i><a href=\"#\" class=\"hidden-sm\">Add to cart</a></p>\r\n");
      out.write("                                        <p class=\"btn-details\">\r\n");
      out.write("                                            <i class=\"fa fa-list\"></i><a href=\"#\" class=\"hidden-sm\">More details</a></p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"clearfix\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <div class=\"col-item\">\r\n");
      out.write("                                <div class=\"photo\">\r\n");
      out.write("                                    <img src=\"Resources/images/marker.jpg\" class=\"img-responsive\" alt=\"a\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"price col-sm-6\">\r\n");
      out.write("                                            <h5>\r\n");
      out.write("                                                Reynolds Pemanent Marker </h5>\r\n");
      out.write("                                            <h5 class=\"price-text-color\">\r\n");
      out.write("                                                &#8377;30.00</h5>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"rating hidden-sm col-sm-6\">\r\n");
      out.write("                                            <i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"separator clear-left\">\r\n");
      out.write("                                        <p class=\"btn-add\">\r\n");
      out.write("                                            <i class=\"fa fa-shopping-cart\"></i><a href=\"#\" class=\"hidden-sm\">Add to cart</a></p>\r\n");
      out.write("                                        <p class=\"btn-details\">\r\n");
      out.write("                                            <i class=\"fa fa-list\"></i><a href=\"#\" class=\"hidden-sm\">More details</a></p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"clearfix\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <div class=\"col-item\">\r\n");
      out.write("                                <div class=\"photo\">\r\n");
      out.write("                                    <img src=\"Resources/images/ashoka stamp pad.jpg\" class=\"img-responsive\" alt=\"a\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"price col-sm-6\">\r\n");
      out.write("                                            <h5>\r\n");
      out.write("                                                Ashoka Stamp Pad</h5>\r\n");
      out.write("                                            <h5 class=\"price-text-color\">\r\n");
      out.write("                                                &#8377;49.99</h5>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"rating hidden-sm col-sm-6\">\r\n");
      out.write("                                            <i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"separator clear-left\">\r\n");
      out.write("                                        <p class=\"btn-add\">\r\n");
      out.write("                                            <i class=\"fa fa-shopping-cart\"></i><a href=\"http://www.jquery2dotnet.com\" class=\"hidden-sm\">Add to cart</a></p>\r\n");
      out.write("                                        <p class=\"btn-details\">\r\n");
      out.write("                                            <i class=\"fa fa-list\"></i><a href=\"http://www.jquery2dotnet.com\" class=\"hidden-sm\">More details</a></p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"clearfix\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"item\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <div class=\"col-item\">\r\n");
      out.write("                                <div class=\"photo\">\r\n");
      out.write("                                    <img src=\"Resources/images/notepad.jpg\" class=\"img-responsive\" alt=\"a\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"price col-sm-6\">\r\n");
      out.write("                                            <h5>\r\n");
      out.write("                                                Note Pad 33 Pages</h5>\r\n");
      out.write("                                            <h5 class=\"price-text-color\">\r\n");
      out.write("                                                &#8377;29.99</h5>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"rating hidden-sm col-sm-6\">\r\n");
      out.write("                                            <i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"separator clear-left\">\r\n");
      out.write("                                        <p class=\"btn-add\">\r\n");
      out.write("                                            <i class=\"fa fa-shopping-cart\"></i><a href=\"#\" class=\"hidden-sm\">Add to cart</a></p>\r\n");
      out.write("                                        <p class=\"btn-details\">\r\n");
      out.write("                                            <i class=\"fa fa-list\"></i><a href=\"#\" class=\"hidden-sm\">More details</a></p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"clearfix\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <div class=\"col-item\">\r\n");
      out.write("                                <div class=\"photo\">\r\n");
      out.write("                                    <img src=\"Resources/images/class mate registers.jpg\" class=\"img-responsive\" alt=\"a\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"price col-sm-6\">\r\n");
      out.write("                                            <h5>\r\n");
      out.write("                                                ClassMate Registers One Set </h5>\r\n");
      out.write("                                            <h5 class=\"price-text-color\">\r\n");
      out.write("                                                &#8377;299.99</h5>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"rating hidden-sm col-md-6\">\r\n");
      out.write("                                       <i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"fa fa-star\"></i>\r\n");
      out.write("                                       \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"separator clear-left\">\r\n");
      out.write("                                        <p class=\"btn-add\">\r\n");
      out.write("                                            <i class=\"fa fa-shopping-cart\"></i><a href=\"#\" class=\"hidden-sm\">Add to cart</a></p>\r\n");
      out.write("                                        <p class=\"btn-details\">\r\n");
      out.write("                                            <i class=\"fa fa-list\"></i><a href=\"#\" class=\"hidden-sm\">More details</a></p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"clearfix\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <div class=\"col-item\">\r\n");
      out.write("                                <div class=\"photo\">\r\n");
      out.write("                                    <img src=\"Resources/images/envelops.jpg\" class=\"img-responsive\" alt=\"a\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"price col-sm-6\">\r\n");
      out.write("                                            <h5>\r\n");
      out.write("                                                 Laminated Envelopes </h5>\r\n");
      out.write("                                            <h5 class=\"price-text-color\">\r\n");
      out.write("                                                &#8377;14.99</h5>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"rating hidden-sm col-sm-6\">\r\n");
      out.write("                                            <i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"separator clear-left\">\r\n");
      out.write("                                        <p class=\"btn-add\">\r\n");
      out.write("                                            <i class=\"fa fa-shopping-cart\"></i><a href=\"#\" class=\"hidden-sm\">Add to cart</a></p>\r\n");
      out.write("                                        <p class=\"btn-details\">\r\n");
      out.write("                                            <i class=\"fa fa-list\"></i><a href=\"#\" class=\"hidden-sm\">More details</a></p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"clearfix\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-3\">\r\n");
      out.write("                            <div class=\"col-item\">\r\n");
      out.write("                                <div class=\"photo\">\r\n");
      out.write("                                    <img src=\"Resources/images/folders.jpg\" class=\"img-responsive\" alt=\"a\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"info\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"price col-sm-6\">\r\n");
      out.write("                                            <h5>\r\n");
      out.write("                                                L folder transparent</h5>\r\n");
      out.write("                                            <h5 class=\"price-text-color\">\r\n");
      out.write("                                                &#8377;14.99</h5>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"rating hidden-sm col-sm-6\">\r\n");
      out.write("                                            <i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"price-text-color fa fa-star\"></i><i class=\"price-text-color fa fa-star\">\r\n");
      out.write("                                            </i><i class=\"fa fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"separator clear-left\">\r\n");
      out.write("                                        <p class=\"btn-add\">\r\n");
      out.write("                                            <i class=\"fa fa-shopping-cart\"></i><a href=\"http://www.jquery2dotnet.com\" class=\"hidden-sm\">Add to cart</a></p>\r\n");
      out.write("                                        <p class=\"btn-details\">\r\n");
      out.write("                                            <i class=\"fa fa-list\"></i><a href=\"http://www.jquery2dotnet.com\" class=\"hidden-sm\">More details</a></p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"clearfix\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr style=\"height:1px; background-color:white;\">\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr style=\"height:1px; background-color:white;\">\r\n");
      out.write("<hr style=\"height:1px; background-color:white;\">\r\n");
      out.write("<hr style=\"height:1px; background-color:white;\">\r\n");
      out.write(" ");
      out.write("<link href=\"Resources/css/footer.css\" rel=\"stylesheet\">\r\n");
      out.write(" \r\n");
      out.write("<link href=\"//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<footer class=\"footer\" style=\"background-color:#26254F;\">\r\n");
      out.write("\t<center><h3 style=\"color:#595959;\">CUSTOMER SUPPORT:+91-9818377157(MON-FRIDAY :9 AM TO 6 PM)</h3></center>\r\n");
      out.write("\t<hr\t>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("   <div class=\"col-sm-3\">\r\n");
      out.write("     <a style=\"decoration:none;\" href=\"aboutus\">ABOUT US</a>  \r\n");
      out.write("   </div>\r\n");
      out.write("   <div class=\"col-sm-3\">\r\n");
      out.write("    <a style=\"decoration:none;\" href=\"contactus\">CONTACT US</a>  \r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-sm-3\">\r\n");
      out.write("    <a style=\"decoration:none;\" href=\"#\">YOUR CART</a>  \r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"col-sm-3\">\r\n");
      out.write("    <a style=\"decoration:none;\" href=\"register\">REGISTER </a>  \r\n");
      out.write("  </div>\r\n");
      out.write("   \r\n");
      out.write("     </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   <hr>\r\n");
      out.write("   <center><h3 style=\"color:#595959;\">FIND US ON</h3></center>\r\n");
      out.write("\t\r\n");
      out.write("\t <div class=\"container text-center\">\r\n");
      out.write("\r\n");
      out.write("        <a href=\"https://www.facebook.com/Manish.Sharma8176\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("        <a href=\"https://twitter.com/i_m_manish_\"><i class=\"fa fa-twitter\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("        <a href=\"#\"><i class=\"fa fa-skype\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("   <hr><H4 style=\"color:white; \"><center>Copyright penandpaper.in © 2009 - 2016  | Website Design by ----Manish Sharma |</center></H4>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
